
export const CONTESTO_TEXT = `
CONTESTO E MOTIVAZIONI DEL BANDO

Verso l’AI definitiva

 Nel 2012 AlexNet, prima rete neurale implementata con GPU e addestrata per una settimana su 1.2 milioni di immagini organizzate in 1.000 categorie, stravince la competizione ImageNet per il riconoscimento di immagini. Gli addetti ai lavori restano sbalorditi, e dopo oltre cinquant’anni di scetticismo e false partenze entriamo nel decennio della ricerca di base sull’AI. Da AlexNet la crescita è stata esponenziale in ogni senso: per esempio, il modello GPT-4 è addestrato su trilioni di token (sia immagini che testo), ha una potenza di calcolo 300mila volte più potente, ha richiesto mesi di addestramento di migliaia di GPU in parallelo con un consumo energetico di una piccola città. Il lancio di chatGPT nel novembre 2022 inaugura il decennio dell’applicazione dell’AI che ha già comportato un impatto sull’economia, la società, la geopolitica paragonabile alla seconda rivoluzione industriale, solo condensato in pochi mesi. CEO, VC, think tank e capi di stato ci dicono che nei prossimi 5 anni vedremo la corsa all’AI “definitiva”, cioè la chiave per un progresso tecnico di scala talmente maggiore di quella attuale da garantire l’egemonia globale.

La nazione che costruirà questa super intelligenza avrà in mano il futuro. Avrà la ricetta per ridurre e quasi annullare i consumi energetici, sintetizzare nuove proteine in pochi minuti, calcolare traiettorie per colonizzare nuovi pianeti e produrre robot che sostituiranno milioni di lavoratori. Al tempo stesso, potrà impedire alle nazioni concorrenti di raggiungere lo stesso potere. Sotto questa lente, battaglie altrimenti economiche quali il veto USA a NVIDIA di vendere le GPU più avanzate alla Cina, le mire espansionistiche della Cina continentale su Taiwan con le sue fabbriche di chip, le guerre per l’accesso a minerali e terre rare, la ricerca di nuove fonti energetiche, il braccio di ferro per l’accesso alle banche dati di produzione umana come i social e i motori di cerca, assumono toni profondamente strategici, a tratti apocalittici.

La tesi umanista dell’AI

In particolare, nel nostro lavoro proponiamo alle imprese una lettura “umanista” del fenomeno AI, cioè la chiusura di una parabola di specializzazione per il ritorno ad un sapere rinascimentale, a tutto tondo. Trascurando per un attimo la potenza di calcolo, ricordiamoci che per far funzionare i primi computer IBM grandi come una stanza erano richiesti facchini, montatori, elettricisti, idraulici, e i primi programmatori di schede bucate, con il carico di studio e addestramento del caso; passando per i semiconduttori, i linguaggi di programmazione sempre più astratti, il personal computer, il mouse, il web con il suo patrimonio di conoscenza e le community di sviluppatori, si è via via consolidata la tecnologia e l’ecosistema per de-specializzare il lavoro necessario a far funzionare il computer, e quindi allargare la base utenti: oggi il 54% della popolazione mondiale ha lo smartphone. L’AI conversazionale è il definitivo traguardo di user experience: oggi per far funzionare il computer ci basta parlare la nostra lingua naturale, cioè ci basta essere quello che già siamo - umani.

E cosa ci resta da imparare, ora che il computer sviluppa ed esegue codice per noi? Principalmente, possiamo migliorare nella traduzione della nostra esigenza pratica in istruzioni esecutive. La commodizzazione dello sviluppo software, con la drastica riduzione di tempi e costi, concentra la competizione sulla capacità di comunicare alla macchina in modo strutturato e non ambiguo per ottenere il comportamento desiderato. Questo problema è sempre esistito e ha dato adito a non pochi attriti e barzellette tra team business e team tech, ma finiva diluito e trascurato nel più grave problema di reperire gli sviluppatori, scrivere il codice, testarlo, migliorarlo.

Homo homini lupus?

Siamo dunque arrivati al migliore dei mondi possibili in cui ogni desiderio diventa realtà? Niente di più lontano. La visione umanistica dell’AI ci restituisce un’economia ancora più spietata in cui, ridotto al minimo l’alibi della complessità tecnica, il successo è strettamente legato alla sola volontà dell’imprenditore senza bisogno di asset pesanti come tecnici, capitali, copertura politica, che finora erano comunque un correlato di credibilità e capacità gestionale, o per lo meno di controllabilità. In altre parole, umanesimo vuol dire anche la possibilità per un lupo solitario di attuare pratiche scorrette, dal furto di proprietà intellettuale, alla costruzione di bombe chimiche, al lancio di campagne d’odio contro competitor, a schemi di evasione fiscale o di truffa, allo sfruttamento del lavoro, in totale autonomia e con un potenziale di scala inaudito. In un mercato neoliberista sempre meno regolamentato e un clima di crescente incertezza del diritto internazionale che premiano la prepotenza e la malizia, l’AI arriva a coronare la tempesta perfetta sollevando l’imprenditore dalla necessità di aggregare una comunità di soci, investitori, lavoratori, clienti, fornitori, banche attorno alla propria volontà e quindi di mediarla, allineandola ad un sentimento morale condiviso.

AI per il terziario: imparare a spiegarsi

In quanto medio-bassa potenza, l’Italia gioca un ruolo marginale nella corsa all’AI definitiva, ma ne subisce le conseguenze quanto tutti gli altri Paesi. La nostra Camera di commercio ha il privilegio di servire il tessuto imprenditoriale non solo più produttivo d’Italia e tra i più produttivi d’Europa, ma anche fortemente polarizzato tra il terziario avanzato e la manifattura, strutture economiche impattate in modo profondamente diverso dall’intelligenza artificiale. Sulle imprese di commercio e servizi Camera ha avviato attività di alfabetizzazione e formazione all’uso di AI già poche settimane dopo il lancio di chatGPT, principalmente per l’originaria funzione text-to-text dello strumento che ben si sposa con la natura intellettuale dei loro processi aziendali. Per queste aziende il cui prodotto o servizio è software o è abilitato da software, ormai accessibile a chiunque, restano due principali fattori di successo:

la strategia, cioè intuire l’idea giusta prima dei competitor
l’esecuzione, cioè realizzarla prima dei competitor

Poiché l’AI è uno strumento eccezionale non solo per lo sviluppo software ma anche per il consolidamento della strategia attraverso la raccolta e l’interpretazione di dati, l’inferenza e il ragionamento, la simulazione di clienti e di scenari, ecco che ridurre al minimo l’attrito nel veicolare le proprie intenzioni alla macchina diventa la competenza chiave. E qual è la figura professionale che esplicita intenzioni con linguaggio naturale? Forse è il nascente profilo del prompt designer, ma più in generale è una mente addestrata a rintracciare le intenzioni dell’autore nel suo linguaggio naturale, sia esso un filosofo greco, un teologo medievale o uno statista del ‘900, e tradurle nello schema di specificazioni di volta in volta più congeniale allo scopo.

A scanso di fraintendimenti, la domanda di ingegneri resta altissima ed è aumentata ulteriormente per quei professionisti in grado di collaborare allo sviluppo dell’AI definitiva, ma è sempre più centralizzata verso i pochi hub di ricerca deep tech tra i quali, ad oggi, Milano non rientra. Al contrario, per una superpotenza millenaria del soft power come l’Italia si aprono nuovi margini competitivi grazie a questo nuovo round di democratizzazione della conoscenza e dello sviluppo software, ora accessibili anche alla micro e piccola impresa che sappia spiegare quello che vuole.

AI per l’artigianato: da mestiere a proprietà intellettuale?

Il nostro territorio non ospita grandi manifatture e giga fabbriche, ma piccole e medie imprese spesso artigiane il cui valore aggiunto risiede nella manualità dei lavoratori, radicata in una lunga tradizione e ottimizzata con l’esperienza individuale. L’AI già in commercio può impattare solo positivamente su queste imprese automatizzando a costo irrisorio i processi amministrativi, potenziando le ricerca di clienti, migliorando il marchio e i contenuti di marketing, insegnando nuove competenze e addirittura supportando lo sviluppo di nuove strategie di crescita. Ben diverso è il discorso dei robot, per cui si può solo osservare e speculare da filosofi. Fino a qualche mese fa il robot più avanzato non sapeva ancora versare un bicchiere d’acqua, mentre un’AI gratuita poteva già negoziare in russo un contratto di distribuzione di merce in esclusiva per l’Uzbekistan meglio dell’avvocato medio, o diagnosticare una tumore meglio di un medico medio. Oggi non è più così. NVIDIA e altri stanno sviluppando modelli di addestramento di AI accuratamente basati sul mondo fisico, i digital twin, velocizzando di diversi ordini di grandezza il tempo di apprendimento dei robot. Nel giro di qualche minuto o ora di addestramento nel mondo virtuale un’AI può imparare a cucinare un piatto, pulire una stanza d’albergo, volteggiare dei birilli nel mondo simulato, per poi essere scaricata nel robot in modo che sappia subito agire nel mondo fisico.

E’ questione di tempo prima che l’AI fisica impari a cucire un abito su misura, restaurare un tavolo antico o preparare dei tortellini ripieni. Questa padronanza fisica, unita alla sterminata conoscenza addestrata sulla infosfera che già riconosciamo di vari chatGPT, renderà i robot dei super artisti in grado non solo di sostituire fedelmente la manodopera artigiana a costi infimi, ma anche di creare nuovi design lavorando con decine di bracci sincronizzati o impiegand sostanze tossiche per l’uomo, corredando il tutto di dettagliate ricerche di mercato, studi di posizionamento, analisi di competitor per lanciare il prodotto. Svilupperanno un proprio stile riconoscibile, produrranno pezzi iconici, vinceranno il Compasso d’Oro, come nell’infosfera vinceranno il nobel.

Mentre la commodizzazione del software ha vissuto una lunga parabola dal primo computer di Turing a chatGPT, per la robotica il salto sarà drastico: i leader dell’industria assicurano che nel giro di mesi, non anni, i robot compariranno nella nostra quotidianità, dalle macchine a guida autonoma, ai camerieri, a cuochi, agli idraulici. L’artigianato smetterà di essere una prerogativa dell’uomo, e il concetto stesso di “fatto a mano” verrà ridefinito. Nel giro di pochi anni l’impresa dovrà dotarsi di questa tecnologia, pena la riduzione delle quote di mercato a una nicchia di collezionisti, ma al contempo potrebbe cogliere una storica finestra di opportunità: la trasformazione del proprio mestiere in una proprietà intellettuale. Chi mai comprerebbe il brevetto di quel particolare tortellino ripieno, quando ci vuole una vita a imparare l’arte e basta un buco nel passaggio generazionale per perdere per sempre il know-how? Ebbene, l’AI fisica promette di imparare una volta per tutte il segreto del tortellino ripieno e di conservarlo per sempre tramandandolo non solo verticalmente alle future generazioni di robot, ma anche orizzontalmente a illimitati cloni ugualmente, perfettamente produttivi. La ricetta segreta diventa improvvisamente un asset per servire un mercato illimitato, proprio come la molecola di un farmaco. 

Sarà il rito di passaggio dell’arte plastica, iniziata col mito di Efesto che forgia lo scudo di Achille, all’era della sua riproducibilità tecnica: come ci ha già insegnato Walter Benjamin per l’arte visiva troveremo altre strade, svilupperemo altri mercati. Si perderà parte dell’aura che oggi ancora avvolge il manufatto, ma i più audaci guadagneranno immense fortune monetizzando la propria tradizione milionaria con Ikea e Ferrero, oppure diventando la nuova Ikea e la nuova Ferrero: inizieranno con il noleggiare costosissimi robot in Saas, difendendo in tribunale la proprietà sui loro dati di addestramento contro le big tech, per poi passare all’acquisto e infine allo sviluppo di robot proprietari, super artigiani del made in italy. Fonderanno fast food multinazionali che serviranno piatti della migliore tradizione a marginalità molto più bassa della trattoria ma con volumi miliardari, e così nella moda e nel mobile. Guideranno un nuovo boom economico al grido di “grande è bello!”, inventando nuove catene del valore e riconfigurando il tessuto sociale. Oppure si estingueranno, lasciando le proprie officine all’archeologia industriale di quando gli antichi “ancora facevano le cose belle a mano”.
`;
