
export const CONTESTO_TEXT = `
CONTESTO E MOTIVAZIONI DEL BANDO


1.	Executive Summary
Il distretto del mobile della Brianza, baluardo storico del manifatturiero italiano, si trova ad affrontare una congiuntura complessa, caratterizzata da un rallentamento del mercato interno e da una crescente volatilità dei costi di produzione. Queste pressioni si sommano a sfide strutturali di lungo periodo, come la carenza di manodopera specializzata e la necessità di una profonda trasformazione digitale e sostenibile. Nonostante questo quadro, l'analisi dimostra una resilienza intrinseca del comparto, che mantiene un ruolo di leadership nazionale e un'elevata propensione all'innovazione.
Il superamento di tali criticità non richiede risposte superficiali, ma un approccio multifattoriale e coordinato:
1.	il potenziamento delle strategie di internazionalizzazione, sfruttando i canali digitali e i mercati ad alta crescita;
2.	l'integrazione pervasiva delle tecnologie dell'Industria 4.0 e della sostenibilità come elementi fondanti del modello di business
3.	il rafforzamento del capitale umano attraverso la formazione mirata e la valorizzazione delle nuove figure professionali.

2.	Andamento e prospettive
Il distretto del mobile della Brianza rappresenta un'eccellenza inconfutabile del panorama economico italiano, con una tradizione secolare che coniuga abilità manuale, design e innovazione tecnologica. Questo territorio si distingue per la sua capacità di generare sinergie tra un manifatturiero altamente innovativo e un'offerta di servizi specializzati, delineando un modello competitivo e bilanciato. I dati ne confermano la leadership: il distretto è leader a livello nazionale per numero di imprese nel settore (1.345 a Monza e Brianza e 833 a Como a fine 2024), coprendo il 40% del fatturato regionale della Lombardia. La sua forza risiede in un ecosistema completo che include produttori di macchinari, studi di design e istituti scolastici dedicati alla formazione specifica. 

3.	Crisi congiunturale del mobilificio artigiano
L'attuale congiuntura storica si inserisce in un contesto di "normalizzazione" post-pandemica. A livello nazionale, il settore del legno-arredo ha chiuso il 2024 con un fatturato totale di 51,7 miliardi di euro, registrando una flessione del 2,9% rispetto all'anno precedente. Nonostante il calo, il valore rimane significativamente superiore ai livelli pre-Covid, testimoniando una profonda resilienza strutturale.

a.	Riduzione domanda interna
L'export ha dimostrato una maggiore solidità, subendo un calo meno marcato (-2,1%) rispetto al mercato interno (-3,3%) che ha subito gli effetti di del ridimensionamento dei bonus fiscali, nonostante la spesa annua per famiglia in mobilio e arredo resti ancora sui 1.600 euro. Le previsioni per il 2025 indicano un cauto ottimismo, con una prevista graduale stabilizzazione grazie alla potenziale ripresa dei consumi delle famiglie e alla diversificazione dei mercati di esportazione.

Indicatore	Valore 2024 (Italia)	Variazione % vs 2023
Fatturato Totale Filiera Legno-Arredo	51,7 mld €	-2,9%
Fatturato Mercato Interno	32,3 mld €	-3,3%
Export Totale Filiera	19,4 mld €	-2,1%
Export Macrosistema Arredamento	14,4 mld €	-1,8%
Saldo Commerciale (Previsione 2025)	8,6 mld €	+744 mln € vs 2019

b.	Aumento costi energia e materie prime
L'aumento del costo dell'energia rappresenta la preoccupazione principale per il 51% delle imprese, e i costi energetici rimangono significativamente più elevati rispetto ai livelli pre-crisi, penalizzando il tessuto produttivo italiano rispetto ai competitor internazionali. Un'indagine di Confcommercio ha rilevato che il 69% delle imprese di Milano, Monza Brianza e Lodi prevede un aumento dell'indebitamento a causa del caro energia, e il 20% teme la chiusura Parallelamente, le aziende hanno subito un'impennata dei prezzi delle materie prime, in particolare del legno, i cui costi sono aumentati fino al 60% in alcuni casi, con un incremento minimo del 30%. Questo, unito alle difficoltà di approvvigionamento, esercita una forte pressione sulla marginalità. L'impatto di questa volatilità non è uniforme, ma crea un divario competitivo: mentre le grandi imprese possono più facilmente assorbire o trasferire questi costi, le piccole imprese artigiane, che costituiscono la spina dorsale del distretto brianzolo, si ritrovano schiacciate tra l'aumento dei costi e la necessità di mantenere prezzi competitivi per non perdere la clientela.

c.	Mancanza di manodopera
Una delle sfide più urgenti è la carenza di manodopera specializzata, un problema che affligge l'intero settore. Le professioni artigianali e tecniche non sembrano più attrattive per i giovani, nonostante l'alta richiesta di figure qualificate. Il settore deve superare lo stereotipo di un lavoro a basso profilo professionale, valorizzando l'integrazione tra competenze manuali e tecnologie avanzate. A questo si aggiunge la delicata questione del passaggio generazionale nelle imprese familiari, che, se non gestito correttamente, può mettere a rischio la continuità aziendale.

4.	Nuove opportunità
Per affrontare le sfide identificate, il mobilificio artigiano brianzolo può percorrere diversi sentieri strategici, molti dei quali sono già in fase di attuazione da parte delle aziende più lungimiranti e di dimensione maggiore. La Camera di commercio interviene proprio a colmare o mitigare le differenti capacità di investimento tra imprese strutturate e botteghe artigiane, che il comparto non può permettersi di lasciare indietro con il loro know-how centenario. L’implementazione di una o più di queste direttrici contribuirà a rilanciare l’attrattività delle professioni artigiane presso i giovani, la vera sfida strategica di queste imprese. Infatti, oltre ad azioni puntuali per venire incontro al linguaggio e alle esigenze dei millennials e della gen Z quali l’attrattività salariale e l’equilibrio vita-lavoro, sono una chiara mission e posizionamento di mercato, sostenibilità del modello di business nel lungo termine, presenza sui mercati esteri e alto contenuto tecnologico a rendere desiderabile l’impresa per i lavoratori e quindi per gli investitori. In ultima analisi, le direttici di seguito descritte sono tasselli di una cultura d’impresa essenziale ad un passaggio generazionale di successo.

a.	Diversificazione geografica e internazionalizzazione
Il potenziale di crescita risiede nei mercati esteri, in particolare negli Stati Uniti, negli Emirati Arabi Uniti, dove il design e la qualità del Made in Italy sono molto apprezzati e la domanda è in crescita. La Cina è un mercato dal grandissimo potenzialmente ma che sta dimostrando una progressiva chiusura ai prodotti italiani, vuoi per una mancata percezione di valore aggiunto o vuoi per errori di posizionamento e di comprensione dei canali promozionali e distributivi.  In un'ottica di medio-lungo periodo, le aziende possono anche valutare la costituzione di joint venture o l'apertura di hub all'estero per una presenza più strutturata. La tabella seguente illustra l'andamento delle esportazioni del settore arredamento, evidenziando la necessità di diversificare e il potenziale di mercati ad alta crescita.

Mercato di Esportazione	Valore 2024 (mld €)	Variazione % vs 2023
Europa (UE)	~10	-
Francia	-	-3,3%
Germania	-	-6,0%
Europa (extra UE)	-	-4,0%
Regno Unito	-	Performance negative
Americhe	2,8	+1,9%
Stati Uniti	-	+1,5%
Canada	-	+6,0%
Altri mercati	-	-
Cina	-	-17,9%
Emirati Arabi Uniti	-	Positivo

b.	Trasformazione digitale e innovazione
Il distretto della Brianza deve affrontare un divario tra la sua ricca tradizione artigianale e la necessità di accelerare la trasformazione digitale. Il settore manifatturiero italiano ha mostrato una notevole propensione all'adozione digitale, con il 72% delle aziende che utilizza almeno una tecnologia avanzata. Tuttavia, permane una differenza significativa tra le grandi imprese, che investono prevalentemente in ricerca e sviluppo, e le PMI, che si concentrano maggiormente su software e processi aziendali. Le tecnologie 4.0, come software di progettazione CAD/CAM, macchine a controllo numerico (CNC) e showroom virtuali, sono essenziali per soddisfare la domanda di personalizzazione e offrire soluzioni "Made to Order", supportate da configuratori digitali sull’e-commerce e da sistemi di tracciabilità ad esempio tramite codici QR e RFID. Questa integrazione tra produzione digitale efficiente e valore artigianale "su misura" è l'elemento chiave che consente di scalare la produzione personalizzata, un'attività che si allinea perfettamente con la vocazione storica del distretto brianzolo. 

c.	Sostenibilità come valore competitivo
La sostenibilità è passata dall'essere un mero optional a una leva competitiva fondamentale. I consumatori moderni, in particolare le nuove generazioni, sono sempre più attenti all'impatto ambientale e alla provenienza dei prodotti. Il distretto brianzolo, con la sua tradizione di qualità e durabilità, possiede un vantaggio intrinseco in questo ambito. La sfida consiste nell'integrare pienamente i principi dell'eco-design, dell'economia circolare e delle certificazioni ambientali nei processi produttivi non come semplici "bollini" ma come strumenti di marketing e comunicazione per creare fiducia e valore percepito, a difesa della concorrenza sul prezzo. L'innovazione nei materiali, da sviluppare con le eccellenze universitarie del territorio, rappresenta una frontiera cruciale per il futuro. L'attenzione alla filiera corta non solo contribuisce all'efficienza operativa e alla riduzione dell'impronta ambientale, ma rafforza anche il legame con il territorio e la sua reputazione di eccellenza e attrattività di lavoratori qualificati.

5.	AI e artigianato
I processi trasformativi sopra descritti preparano l’impresa artigiana ad affrontare la rivoluzione manifatturiera che si profila all’orizzonte dell’innovazione, indicato dai leader di settore in termini di mesi o anni: l’AI fisica, cioè l’inserimento del “cervello” con cui già interagiamo in chat in macchine capaci di movimento autonomo e “generativo”. Non sappiamo esattamente quale tecnologia sarà e come arriverà sul mercato, ma la sua portata sarà certamente dirompente e vogliamo che le nostre imprese siano preparate al meglio a comprenderla e ad adattarsi. Vogliamo che quanti più imprenditori siano in grado di sfruttare la finestra di opportunità che si potrebbe aprirsi e che, nelle dichiarazione dei capi di stato e di industria, sarà paragonabile alla prima applicazione della macchina a vapore alla tessitura e alla navigazione, o alla prima disponibilità del personal computer per tenere la contabilità, o alla prima accessibilità di mercati lontani grazie all’e-commerce. La piccola impresa artigiana ha nella velocità di decisione e nel suo storico know-how un vantaggio competitivo ai grandi gruppi industriali, a patto di maturare quella lucidità di visione necessaria a raccogliere il capitale finanziario e umano necessari al salto di qualità. Questa attitudine all’innovazione non ce la si dà in un giorno, ma si costruisce in mesi e anni di aggiornamento dei processi e delle competenze.

a.	Verso l’AI definitiva
Nel 2012 AlexNet, prima rete neurale implementata con GPU e addestrata per una settimana su 1.2 milioni di immagini organizzate in 1.000 categorie, stravince la competizione ImageNet per il riconoscimento di immagini. Gli addetti ai lavori restano sbalorditi, e dopo oltre cinquant’anni di scetticismo e false partenze entriamo nel decennio della ricerca di base sull’AI. Da AlexNet la crescita è stata esponenziale in ogni senso: per esempio, il modello GPT-4 è addestrato su trilioni di token (sia immagini che testo), ha una potenza di calcolo 300mila maggiore, ha richiesto mesi di addestramento di migliaia di GPU in parallelo con un consumo energetico di una piccola città. Il lancio di chatGPT nel novembre 2022 inaugura il decennio dell’applicazione dell’AI con un epocale impatto sull’economia, la società e la geopolitica. CEO, VC, think tank e capi di stato ci dicono che nei prossimi 5 anni vedremo la corsa all’AI “definitiva”, o super umana, cioè la chiave per un progresso tecnico di scala talmente maggiore di quella attuale da garantire l’egemonia globale.

La nazione che costruirà questa super intelligenza avrà in mano il futuro. Avrà la ricetta per ridurre e quasi annullare i consumi energetici, sintetizzare nuove proteine in pochi minuti, calcolare traiettorie per colonizzare nuovi pianeti e produrre robot che sostituiranno milioni di lavoratori. Al tempo stesso, potrà impedire alle nazioni concorrenti di raggiungere lo stesso potere. Sotto questa lente, battaglie altrimenti economiche quali i dazi sull’import, il veto USA a NVIDIA di vendere le GPU più avanzate alla Cina, le mire espansionistiche della Cina continentale su Taiwan con le sue fabbriche di chip, le guerre per l’accesso a minerali e terre rare, la ricerca di nuove fonti energetiche, il braccio di ferro per l’accesso alle banche dati di produzione umana come i social e i motori di cerca, assumono toni profondamente strategici.

b.	La tesi umanista dell’AI
Proponiamo una lettura “umanista” del fenomeno AI per la micro impresa, come chiusura di una parabola di specializzazione e il ritorno ad un sapere “rinascimentale”, a tutto tondo. Per far funzionare i primi computer IBM grandi come una stanza erano richiesti facchini, montatori, elettricisti, idraulici e programmatori di schede bucate lungamente addestrati; passando per i semiconduttori, i linguaggi di programmazione sempre più astratti, il personal computer, il mouse, il web con il suo patrimonio di conoscenza e le community di sviluppatori e utenti, si è via via consolidata la tecnologia e l’ecosistema per de-specializzare il lavoro necessario a far funzionare il computer, e quindi allargare la base utenti: oggi il 54% della popolazione mondiale ha lo smartphone e il 69% ha accesso a internet, mentre il 15% è analfabeta e il 25% non ha accesso sicuro all’acqua potabile. L’AI conversazionale è il definitivo traguardo di user experience: oggi per far funzionare il computer ci basta parlare, neanche scrivere, la nostra lingua naturale. Le barriere all’interazione uomo-macchina sono definitivamente annullate e così micro imprese e singoli individui hanno finalmente accesso a tutte le potenzialità tecnologiche che fino a qualche mese fa avevano costi proibitivi.

c.	Da sapere a volere
Umanismo vuole anche dire spostare il focus dell’attività umana, soprattutto di business, dal sapere nozioni all’avere delle intenzioni. Così come dopo l’introduzione della calcolatrice non era più produttivo saper fare di conto su carta, così dopo l’AI conversazionale, e a breve quella super umana, non è più produttivo sapere…nulla: una chat con intelligenza e conoscenza migliore di qualunque scienziato, politico, finanziere, grafico umano che sia mai esistito mette fuori mercato qualunque professione basata sul sapere cose. Viceversa, mai come oggi la produttività coincide con la volontà imprenditoriale: cosa va fatto e perché. Infatti, per quanto l’AI possa suggerirci strategie e supportarle con dati, la decisione ultima resta dell’imprenditore, del manager, dell’impiegato nel proprio livello di responsabilità.

In questo repentino cambio delle regole di produttività, il principale fattore competitivo risiede nella capacità di veicolare le nostre intenzioni all’AI. Poichè l’interfaccia di comunicazione è conversazionale, ciò si traduce nella padronanza linguistica: lavora meglio chi sa spiegarsi meglio. Possiamo chiamarlo “prompt design”, ma altro non è che la capacità di tradurre le nostre intenzioni in istruzioni esecutive non ambigue e non una volta sola, ma lungo iterazioni di feedback su come aggiustare l’output fino al risultato desiderato. Va da sé che il processo sarà tanto veloce quanto le nostre intenzioni di partenza erano chiare: commodizzata la conoscenza e la complessità tecnica che prima fungevano da “rumore di fondo”, mai come oggi sono le scelte di business i responsabili del successo e del fallimento.

d.	Digital twin per velocizzare l’addestramento
Il nostro territorio non ospita grandi manifatture e giga fabbriche, ma piccole e medie imprese spesso artigiane il cui valore aggiunto risiede nella manualità dei lavoratori, radicata in una lunga tradizione e ottimizzata con l’esperienza individuale. L’AI già in commercio può impattare positivamente su queste imprese automatizzando a costo irrisorio i processi amministrativi, potenziando le ricerca di clienti, migliorando il marchio e i contenuti di marketing, insegnando nuove competenze e addirittura supportando lo sviluppo di nuove strategie di crescita, cioè in tutte le funzioni intellettuali. Ben diverso è il discorso per le funzioni produttive, in cui la robotica può intervenire con un grado di autonomia limitato e quindi su catene di montaggio tipiche dell’industria, non dell’artigianato. L’impedimento principale alla sostituzione dell’artigiano con il robot sono le difficoltà di programmarlo a uno spettro così ampio di gesti, impattati da così tante variabili. L’insieme delle capacità di discernere ciascuna di queste variabili e adattare il lavoro attraverso una miriade di micro-decisioni e conseguenti modulazioni del gesto, diretto o indiretto attraverso attrezzi e macchinari, e ciò che intendiamo come “mestiere”.

Fino a qualche mese fa il robot più avanzato faticava a imparare nuovi gesti per cui non era esplicitamente programmato perché ogni tentativo, su cui si vengono calibrati i nodi del suo “cervello” fino al gesto perfetto, richiedeva il tempo del gesto stesso: moltiplicato per i milioni di tentativi necessari, il perfezionamento di un gesto lungo e complesso richiedeva anni di prove ed errori in laboratorio. Oggi non è più così. NVIDIA, Blender, Autodesk altre aziende tech hanno sviluppato modelli di addestramento di AI accuratamente basati sul mondo fisico, i digital twin, in cui il “cervello” del robot senza un “corpo” può simulare il gesto ricevendo un feedback virtuale identico a quello fisico, ma iterando l’operazione alla velocità della GPU di milioni o miliardi di tentativi virtuali al minuto. Nel giro di qualche minuto o ora di addestramento nel mondo virtuale un’AI può imparare a cucinare un piatto, pulire una stanza d’albergo, volteggiare dei birilli, per poi essere scaricata nel robot, il “corpo”, che sarà pronto per agire nel mondo. Questa nuova frontiera dell’AI fisica (o “incorporata”, dall’inglese “embodied”), promette tra le altre cose di sostituire i mestieri artigiani finora inespugnabili.

e.	Da mestiere a proprietà intellettuale
Proprio come vediamo l’AI conversazionale scrivere poesie e codice meglio di noi, le aziende leader ci assicurano che a breve vedremo l’AI fisica cucire un abito su misura e lavorare la gamba di un tavolo meglio di noi. Se questo è verosimile, dobbiamo attenzionare il fenomeno per anticiparne le conseguenze sul nostro tessuto imprenditoriale, perché sarebbero epocali: l’artigianato smetterebbe di essere una prerogativa dell’uomo, e il concetto stesso di “fatto a mano” verrebbe ridefinito. Nello scenario che ci restituiscono i leader della AI e della robotica, nel giro di pochi anni la nostra impresa dovrà dotarsi di questa tecnologia, pena la riduzione delle quote di mercato a una nicchia di collezionisti. Ma al contempo potrebbe cogliere una storica finestra di opportunità: la trasformazione del proprio mestiere in una proprietà intellettuale. Oggi e per millenni il mestiere si tramanda in bottega di generazione in generazione con milioni di ore di pratica tra umani, rendendolo altamente difendibile ma fragile, perché basta un salto nella catena della trasmissione del know-how per perderlo per sempre, e in-scalabile su grandi volumi. Per questo il mestiere artigiano, anche quando ad alta marginalità, non è attrattivo per i grandi capitali. Inoltre, mentre l’AI conversazionale è stata addestrata, con diverse controversie morali e legali, sulla proprietà intellettuale depositata da tutti noi sul web o raccolta in database digitali privati come quelli di Google, Meta, Amazon, Alibaba, l’AI fisica non ha accesso alla proprietà intellettuale dei mestieri: per disinteresse, sconvenienza costi-benefici o gelosia, pochi artigiani monitorano i propri processi produttivi con sensori e strumentazione 4.0 e comunque lo farebbero a una granularità troppo bassa per addestrare un’AI fisica. 

Lo scenario prospettato dagli sviluppi di mondi fisici virtuali per l’addestramento di macchine intelligenti, in un mercato della robotica che vale oggi 100 miliardi di dollari e un CAGR del 300% in 5 anni, aprirebbe un vertiginoso potenziale per quegli artigiani che sappiano depositare e proteggere il proprio know-how in questi mondi virtuali, vendendolo su licenza a terzi o custodendolo gelosamente per insegnare l’arte solo ai propri robot. Si potrebbe sviluppare un “mercato della manualità” come branca del mercato dei dati sintetici per l’addestramento dell’AI, stimato in 500 milioni di dollari e con un CAGR del 500% in 5 anni. Da serie limitate avrebbero immediatamente sbloccato produzioni personalizzate, “a regola d’arte”, su volumi illimitati, con conseguente accesso al grande capitale e a moltiplicatori di crescita da startup e poi da industria. 

Ogni mestiere dovrebbe investire nei propri metodi e tecnologie per digitalizzare il proprio know-how, per alcuni saranno telecamere che filmano ogni movimento, per altri una varietà di sensori installati sugli attrezzi di lavorazione e sul pezzo lavorato, per altri ancora saranno semplici interviste agli operai e ai capi mastri accuratamente tradotte dall’AI in istruzioni operative, ma il denominatore comune per abbracciare questa strada sarà l’apertura mentale al cambiamento e l’abitudine all’apprendimento continuo, qualità che vanno sviluppate da subito su tutti gli altri fronti di competizione già aperti e sopra descritti.
`;
